### ISSUE TITLE
Support ADAL/Modern Authentication Credential Popup

### ISSUE THREAD

**Issue by rswafford** [MscrmTools/MscrmTools.Xrm.Connection#104]
Are there plans to add support for the D365/Azure AD "modern authentication" credential window? Our organization has disabled "legacy" authentication so we're limited now to either the modern auth experience, or pure OAuth which of course requires an administrator to configure client secrets for each user.

https://docs.microsoft.com/en-us/office365/enterprise/office-365-client-support-modern-authentication

https://docs.microsoft.com/en-us/azure/active-directory/develop/reference-v2-libraries

**Comment by MscrmTools** [comment]
I do not have to handle anything since I'm just using XRM SDK libraries. If XRM Tooling handles it, you should be able to use it.
At least by using connection string or SDK login, you should be able to connect to your organization. If not, it means that XRM Tooling does not handle it, so I can't either.
I may have to do some work to allow connection wizard (the only one which uses custom code) to use it

**Comment by rappen** [comment]
Not sure if this helps (as I'm not very skilled in auth things) but this code is used in Power Apps Checker to authenticate to Azure AD with interactive user login:
https://github.com/rappen/PowerAppsChecker/blob/master/PowerAppsChecker/PACHelper.cs#L79-L89

**Comment by rswafford** [comment]
After further testing, it seems we need to create a whole new connection - simply editing an existing D365 connection won't let the Modern Auth dialog pop up.
