### ISSUE TITLE
Connection string automatically modifies to different enviro

### ISSUE THREAD

**Issue by jimphuebner** [MscrmTools/MscrmTools.Xrm.Connection#79]
My previous connection string to our PROD environment now connects to my trial instance.
The names are similar...
PROD (previously working v.8.2) 
- https://orgname.crm.dynamics.com

TRIAL (recently created instance V9.0, but no connection created in XrmToolBox)
- https://orgname0.crm.dynamics.com

Note: I also have a DEV v.8.2 which has no connection problem.
- https://dorgname365.crm.dynamics.com

I attempted the following:
1) delete the trial and recreate the PROD connection - always reverts back to TRIAL
2) manually edit the connections file - add PROD connection, also change all connection strings, org name, version, etc. to match our v8.2 DEV
- result - always changes the string to TRIAL instance.

I believe this has something to do with the discovery service redirecting to the wrong instance and the names being similar, but there doesn't seem to be a way to manage this.

**Comment by zenecamickeyd** [comment]
This morning I discovered that I have the same issue.  Whenever I connect to our Production instance I'm actually being connected to our Sandbox instance.  Both our Production and Sandbox instances are online v9.0.

**Production** 
URL = https://acmeltd.crm4.dynamics.com
Unique Name = org58bd7c9z

**Sandbox**
URL = https://acmeltdtest.crm4.dynamics.com
Unique Name = acmeltd

I've configured the Production connection to use Production's unique name in the Organization URL (https://org58bd7c9z.crm4.dynamics.com), but when I edit the Production connection the Organization URL has been changed to https://acmeltd.crm4.dynamics.com and connects to Sandbox.  I think this caused by the Production URL containing Sandbox's unique name.
