### ISSUE TITLE
Unable to connect - Version 1.2019.2.32

### ISSUE THREAD

**Issue by hamhus** [MscrmTools/MscrmTools.Xrm.Connection#89]
I can't connect to the Ribbon workbench 2016 after installing the new version. 
Screenshot attached.
![XrmToolBox_Error](https://user-images.githubusercontent.com/18374071/56832950-1743b200-6822-11e9-90db-bb07e5c72f52.PNG)

**Comment by MscrmTools** [comment]
I used it yesterday without any issue

How was the connection created?

**Comment by hamhus** [comment]
Through SDK Login Control

**Comment by imranakram** [comment]
Hi,
I just experienced this now with a connection string that has been working for over a month now, and it was working with the same XTB version. I have tried with Connection Wizard and Connection String. XTB version is 1.2019.2.32 and the target environment is CRM Online with **April 2019 updates enabled**

Note that this is working correctly for CRM online without April 2019 updates

Here's the error from the log

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	4/29/2019 12:46:24 PM  Unable to connect to CRM: An error occurred when processing the security tokens in the message:Authorization failed
Source	: mscorlib
Method	: HandleReturnMessage
Date	: 4/29/2019
Time	: 12:46:24 PM
Error	: An error occurred when processing the security tokens in the message:Authorization failed
Stack Trace	: Server stack trace: 
   at System.ServiceModel.Channels.ServiceChannel.HandleReply(ProxyOperationRuntime operation, ProxyRpc& rpc)
   at System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   at System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   at System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.GetWhoAmIDetails(IOrganizationService crmService, Guid trackingID)
   at Microsoft.Xrm.Tooling.Connector.CrmWebSvc.InitCRM2011Service()
======================================================================================================================

Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	4/29/2019 12:46:24 PM  Unable to Login to Dynamics CRM
Microsoft.Xrm.Tooling.Connector.CrmServiceClient	Error	2	4/29/2019 12:46:24 PM  Unable to Login to Dynamics CRM
Source	: Not Provided
Method	: Not Provided
Date	: 4/29/2019
Time	: 12:46:24 PM
Error	: Unable to Login to Dynamics CRM
Stack Trace	: Not Provided

**Comment by imranakram** [comment]
I have initiated a support request with Microsoft

**Comment by shytikov** [comment]
Ok,

I tried to debug it and approached from different directions. And I have only one idea why it's happening — internal issues in CRM SDK. Not sure how we can fix it — all packages are updated already, we need to report this issue to MS and wait for resolution.

But apparently it won't be possible to connect to CRM April release using command line too...

---

Now to the fix, or rather workaround.

You still would be able to connect to CRM using SDK Login control. Yes it's clumsy, but at least it works now.

**Comment by MscrmTools** [comment]
So this is not an issue with the SDK but a new direction taken by the SDK.
OrganizationServiceProxy should not be used anymore but only CrmServiceClient.
That means that each Plugin developer needs to adapt his code to avoid using OrganizationServiceProxy

**Comment by shytikov** [comment]
But we're not using `OrganizationServiceProxy` (explicitly) here. It's used by SDK internally to get information about `WhoAmI` request. Which is failing.

I've noticed the fact that `OrganizationServiceProxy` is null when we're connecting to Online environments, since I believe SDK will use `OAuth` on the background, but I was always able to connect. Now — not anymore... I believe we would need either not use `Xrm.Tooling` anymore, or wait for a fix from MS.

**Comment by shytikov** [comment]
@MscrmTools I got it... we're talking about two different bugs!!!

We with @imranakram  cannot connect to Online instance with April release unless connection is initiated via SDK Login Control...

**Comment by imranakram** [comment]
Now we can connect to our CRM online environment via SDK/XrmToolBox. The issue was related to some issue in synchronization between AD and O365 user. This is resolved by unassigning CRM license from the user, waiting until we're unable to login from browser then assigning the licenses back to the user. This forces synchronization to occur. According to MS Support, they have seen similar issue in on-premise environments as well. Note that it took between 8-20 minutes in our case to take effect after the licenses were revoked and assigned. Normally it's supposed to take 5-10 minutes

**Comment by MscrmTools** [comment]
Thank you for the feedback and the help.

I’m glad the issue was not on XrmToolBox side :)
